### ISSUE TITLE
Rearding https://pypi.org/project/chess/

### ISSUE THREAD

**Issue by niklasf** [doismellburning/chess#3]
Hi there,

a few years ago I tried to contact you via email, regarding https://pypi.org/project/chess/. Since I could not reach you, I figured I'll try again via this channel.

This project appears to be unmaintained. Meanwhile the namespace would be really useful for my library https://github.com/niklasf/python-chess (currently published as https://pypi.org/project/python-chess/), which offers a superset of the functionality.

Would you consider giving up the namespace?

Apologies if you have other plans for the package. Just let me know if you do not wish to be contaced about this again.

Best,
Niklas

**Comment by doismellburning** [comment]
Hello! I'm very sorry, I hadn't seen that email - my spam filters for addresses visible on PyPI have ended up needing to be fairly aggressive, my apologies.

Your library looks excellent, and far more fitting of the `chess` name than my initial fumblings here - by all means! I never got very far with this and that's unlikely to change any time soon.

I'd be surprised if anyone actually uses it, so I can't imagine we need to do much work around any kind of "transfer management" - on that basis I've sent you an invitation to be the "Owner" of the PyPI project - feel free to do whatever you feel appropriate, whether that's deleting and recreating, removing me, uploading yours over the top of it, or something else.

Finally, I'd like to thank and commend you for your patience (my apologies again!) and for your thoughtfulness and consideration when approaching this (per niklasf/python-chess#678).

If there's anything else I can do here, please let me know!

**Comment by niklasf** [comment]
Thank you, much appreciated! I'll adjust links and upload the current release soon. Given that it will differ in the major version number, I see no reason to delete historical data.
